on: [push]

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - name: Test database connection
        run: |
          # for psql
          sudo apt-get install -y postgresql-client
          # Test psql connection
          PGPASSWORD=egen_poc psql -h egen-rds.cmpvw21itcfn.us-east-1.rds.amazonaws.com -p 5432 -U egen -d egen -c "select 1"
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v5
        with:
          operation: 'update'
          classpath: '/liquibase/changelog'
          changeLogFile: 'changelogs/changelog.xml'
          username: 'egen'
          password: 'egen_poc'
          url: 'jdbc:postgresql://egen-rds.cmpvw21itcfn.us-east-1.rds.amazonaws.com:5432/egen'
