on: [push, pull_request]

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    container: node:latest
    services:
      postgres:
        image: postgres:latest
        # `POSTGRES_HOST` is `postgres`
        env:
          POSTGRES_DB: postgres_db
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_PORT: 5432
          POSTGRES_USER: ${{ secrets.DB_USERNAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v5
        with:
          operation: 'update'
          classpath: 'changelogs'
          changeLogFile: 'changelog.xml'
          username: ${{ secrets.DB_USERNAME }}
          password: ${{ secrets.DB_PASSWORD }}
          url: ${{ secrets.DB_URL }}
