on: [push]

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v5
        with:
          operation: 'update'
          classpath: 'changelogs'
          changeLogFile: 'changelog.xml'
          username: 'egen'
          password: 'egen_poc'
          url: 'jdbc:postgresql://egen-rds.cmpvw21itcfn.us-east-1.rds.amazonaws.com:5432/egen'
